title: Abyssal Website
description: Abyssal Website
remote_theme: just-the-docs/just-the-docs

url: https://warpedentrance.github.io/SCPFABYSSAL/
logo: "/images/logos/foundation-logo.png"
footer_content: "Copyright &copy; 2020-2024 Agent's SCP Foundation."
color_scheme: scpf


callouts:
  important:
    title: Important
    color: red
  caution:
    title: Caution
    color: yellow
  hint:
    title: Hint
    color: green
  information:
    title: Information
    color: blue

last_edit_timestamp: true
search_enabled: false

gh_edit_link: true
gh_edit_link_text: "Edit Docs"
gh_edit_repository: "https://github.com/WarpedEntrance/SCPFABYSSAL"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "edit"

aux_links:
  Main Group: https://www.roblox.com/groups/10693806/SCP-F-Special-Containment-Procedures-Foundation#!/about
  A37: https://www.roblox.com/games/17401541711/Area-37v1
